version: '3'
services:
    web:
        image: webdevops/php-apache-dev:latest
        container_name: web
        restart: always
        environment:
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - ./public_html/:/app
        ports:
          - "${HTTP_PORT}:80"
          - "${HTTPS_PORT}:443"
          - "${SSH_PORT}:22"
        links:
          - mysql
    mysql:
        image: mariadb:10
        container_name: mysql
        restart: always
        ports:
          - "${MYSQL_PORT}:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=test
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "${PHPMYADMIN_PORT}:80"
        links:
          - mysql:db
        depends_on:
          - mysql

volumes:
    db-data:
        external: false